apiVersion : apps/v1
kind: Deployment
metadata:
  name: pinakiukazuredevops 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinakiukazuredevops
  template:
    metadata:
      labels:
        app: pinakiukazuredevops 
    spec:
      containers:
        - name: pinakiukazuredevops 
          image: pmmyregistry.azurecr.io/pinakiukaksvirtualkubelet
          ports:
          - containerPort: 80
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists

